#!/bin/sh

# Instructions to access this from scratch
#     svn co -N svn+ssh://svn.cern.ch/reps/tdr2 myDir
#     cd myDir
#     svn update utils
#     svn update -N notes
#     svn update notes/SMP-12-013

# Working with this:
#     cd myDir/notes/SMP-12-013/trunk
#     MAKENOTE
#     VIEWIT

eval `../../tdr runtime -sh`

tdr --style=paper --nodraft b SMP-12-013
#tdr --style=paper --aps=prl,twocolumn,aps,linenumbers,twoside,amsfonts,amssymb,amsmath b SMP-12-015 
