#!/bin/sh

# Instructions to access this from scratch
#     svn co -N svn+ssh://svn.cern.ch/reps/tdr2 myDir
#     cd myDir
#     svn update utils
#     svn update -N notes
#     svn update notes/HIG-12-021

# Working with this:
#     cd myDir/notes/HIG-12-021/trunk
#     MAKENOTE
#     VIEWIT

eval `../../tdr runtime -sh`

#tdr --style=paper --nodraft b HIG-12-021
tdr --style=paper b HIG-12-021
